config/routes.rb
SJYABackOffice::Application.routes.draw do
  resources :organizations

  resources :users do
    member do
      post 'invite', to: 'invites#create', as: :invite
      delete 'uninvite', to: 'invites#destroy', as: :uninvite
      get 'register/:invite_code', to: 'invites#edit', as: :rsvp
      match 'register', to: 'invites#update', via: [:patch, :put], as: :register
      match 'revoke', to: 'users#revoke', via: [:patch, :put], as: :revoke
    end
  end

  resources :documents do
    get 'download', on: :member, as: :download
  end

  resources :measures, except: [:show] do
    resources :measurements, except: [:index, :show]
  end
  get 'dashboard', to: 'measures#index', as: :dashboard

  resources :reports, only: [:index, :show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'cache/clear', to: 'cache#clear', as: :clear_caches

  get 'about', to: 'static_pages#about', as: :about
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout


  get 'reports', to: 'static_pages#reports', as: :reports
  get 'activity_summary', to: 'static_pages#activity_summary', as: :activity_summary
  get 'coalition_report', to: 'static_pages#coalition_report', as: :coalition_report
  get 'coalition_meeting_report', to: 'static_pages#coalition_meeting_report', as: :coalition_meeting_report
  get 'major_matrix_report', to: 'static_pages#major_matrix_report', as: :major_matrix_report
  get 'strategy_report', to: 'static_pages#strategy_report', as: :strategy_report

  mount Rapidfire::Engine => "/rf"

  root to: 'measures#index'
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def reports
  end

  def coalition_report

    @report = {}
    # {"IT" => {members: 30, involvement: 30}}

    if Rapidfire::Attempt.present?
      Rapidfire::Attempt.all.each do |at|

        at.answers.find_by(question_id: 5).answer_text.split(',').reject(&:blank?).each do |sector_id|
          sector = Sector.find(sector_id.to_i).name
          @report[sector] ||= Hash.new(0)
          #@report[sector][:involvement] = ((Rapidfire::Answer.where(answer_text: sector_id).count * 100) / Rapidfire::Attempt.count.to_f).round(2)
          @report[sector][:involvement] += 1
          answer_row = at.answers.find_by(question_id: 6)
          members = answer_row.answer_text.to_i
          @report[sector][:members] += members
        end

      end
    end

    @report[:involvement_total] = @report.each_key.inject(0) { |sum, sector| sum + @report[sector][:involvement] }

  end

  def activity_summary
    @summary = {}

    if params[:start_date] and params[:end_date].present?
      activities = Rapidfire::Attempt.where("activity_date >= ? AND activity_date <= ?", params[:start_date], params[:end_date])
      activities.each do |at|
        activity = at.activity_type
        @summary[activity] ||= Hash.new(0)
        @summary[activity][:period] += 1
        @summary[activity][:stop_act] += at.completed_for.include?('Stop ACT') ? 1 : 0
        @summary[activity][:drug_free] += at.completed_for.include?('Drug Free Communities') ? 1 : 0
        @summary[activity][:participants] += at.answers.find_by(question_id: 6).answer_text.to_i
        @summary[activity][:adult] += at.answers.find_by(question_id: 12).answer_text.to_i
        @summary[activity][:youth] += at.answers.find_by(question_id: 13).answer_text.to_i
        @summary[activity][:very] += at.answers.find_by(question_id: 1).answer_text == 'Very Successful' ? 1 : 0
        @summary[activity][:moderate] += at.answers.find_by(question_id: 1).answer_text == 'Moderately Successful' ? 1 : 0
        @summary[activity][:not_successful] += at.answers.find_by(question_id: 1).answer_text == 'Not at All Successful' ? 1 : 0
      end
    else
      Rapidfire::Attempt.all.each do |at|
        activity = at.activity_type
        @summary[activity] ||= Hash.new(0)
        @summary[activity][:period] += 1
        @summary[activity][:stop_act] += at.completed_for.include?('Stop ACT') ? 1 : 0
        @summary[activity][:drug_free] += at.completed_for.include?('Drug Free Communities') ? 1 : 0
        @summary[activity][:participants] += at.answers.find_by(question_id: 6).answer_text.to_i
        @summary[activity][:adult] += at.answers.find_by(question_id: 12).answer_text.to_i
        @summary[activity][:youth] += at.answers.find_by(question_id: 13).answer_text.to_i
        @summary[activity][:very] += at.answers.find_by(question_id: 1).answer_text == 'Very Successful' ? 1 : 0
        @summary[activity][:moderate] += at.answers.find_by(question_id: 1).answer_text == 'Moderately Successful' ? 1 : 0
        @summary[activity][:not_successful] += at.answers.find_by(question_id: 1).answer_text == 'Not at All Successful' ? 1 : 0
      end
    end
  end

  def major_matrix_report
    @records = {}
    if params[:start_date] and params[:end_date].present?
      records = Rapidfire::Attempt.where("activity_date >= ? AND activity_date <= ?", params[:start_date], params[:end_date])
      records.each do |at|
        activity = at.answers.find_by(question_id: 2).answer_text
        @records[activity] ||= Hash.new(0)
        @records[activity][:count] += 1
      end
    else
      Rapidfire::Attempt.all.each do |at|
        activity = at.answers.find_by(question_id: 2).answer_text
        @records[activity] ||= Hash.new(0)
        @records[activity][:count] += 1
      end
    end
    @activities = Hash[(@records.sort_by { |key, record| record[:count] }).reverse]
  end

  def strategy_report
    @records = {}
    if params[:start_date] and params[:end_date].present?
      records = Rapidfire::Attempt.where("activity_date >= ? AND activity_date <= ?", params[:start_date], params[:end_date])
      records.each do |at|
        activity = at.answers.find_by(question_id: 4).answer_text
        @records[activity] ||= Hash.new(0)
        @records[activity][:count] += 1
      end
    else
      Rapidfire::Attempt.all.each do |at|
        activity = at.answers.find_by(question_id: 4).answer_text
        @records[activity] ||= Hash.new(0)
        @records[activity][:count] += 1
      end
    end
    @activities = Hash[(@records.sort_by { |key, record| record[:count] }).reverse]
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.haml
- title "About Us"

.row
  .col-xs-12
    %p.lead
      The St. Joseph Drug Free Community Coalition (DFC), with the St. Joseph Youth Alliance (Youth Alliance),
      began implementing intensive resource/coalition development strategies in 2002 to combat youth
      substance use.  Since 2004, the coalition has made significant progress toward their mission:

.row
  .col-xs-12
    %blockquote.col-md-6
      We work together to positively change community attitudes and behaviors surrounding drugs, alcohol
      and tobacco, ultimately encouraging youth to choose substance-free lives.

.row
  .col-xs-12
    %p.lead
      Youth substance use prevention has been one of the two primary areas of focus for the coalition since
      2004.  The coalition focuses on youth asset development, community awareness, coalition capacity and
      environmental change.  DFC recognizes the strong correlation between prevention and youth assets,
      forming a strategic plan around strategies that capitalize on building protective factors (service
      learning, parental involvement, community awareness) and reducing risk factors (environmental changes,
      reduced stress, ordinances).  Although past efforts have primarily focused on access to alcohol by
      youth and underage drinking with limited focus on tobacco prevention, trends and attitudes in our
      community has prompted DFC to expand its tobacco efforts and to also include marijuana/synthetic
      marijuana, and to monitor the use of prescription drugs.

    %p.lead DFC accomplishes its work using these four committees:

    %ul
      %li
        %strong Common Message Committee
      %li
        %strong Marketing & Media Committee
      %li
        %strong Plan of Action Committee
      %li
        %strong Key People Committee

app/views/static_pages/activity_summary.html.haml
- title "Activity Summary"

= form_tag activity_summary_path, method: :get do
  .row
    .col-md-12
      .form-group
        .col-md-10
          %table{style: 'width: 100%'}
            %tr
              %td.c{style: 'width: 15%'}
                %strong Search :
              %td{style: 'width: 35%'}
                = text_field_tag :start_date, '', class: 'form-control', data: { 'date-format' => 'yyyy-mm-dd' }, placeholder: 'Date From'
              %td{style: 'width: 35%'}
                = text_field_tag :end_date, '', class: 'form-control', data: { 'date-format' => 'yyyy-mm-dd' }, placeholder: 'Date To'
              %td.c{style: 'width: 15%'}
                = submit_tag('Search', class: 'btn btn-primary')



.row
  %br
  .col-md-12
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th.c Activity Type
          %th.c # in Period
          %th.c Completed for
          %th.c Total Participants
          %th.c Volunteer Hours
          %th.c Sectors
          %th.c Successfulness
      %tbody
        %tr
          %td.c
          %td.c
          %td.c
            %table
              %tr
                %th.c % for Stop Act
                %th.c % Drug Free Community
          %td.c
          %td.c
            %table{style: 'width: 100%;'}
              %tr
                %th.c Adults
                %th.c Youth
          %td.c
            %table{style: 'width: 100%;'}
              %tr
                %th.c{style: 'width: 50%'} Count
                %th.c{style: 'width: 50%'} %
          %td.c
            %table
              %tr
                %td.c{colspan: 2} Very Successful
                %td.c{colspan: 2} Moderately Successful
                %td.c{colspan: 2} Not at All Successful
              %tr
                %th.c #
                %th.c %
                %th.c #
                %th.c %
                %th.c #
                %th.c %

        - @summary.each_key do |activity|
          %tr
            %td.c= activity
            %td.c= @summary[activity][:period]
            %td.c
              %table{style: 'width: 80%;'}
                %tr
                  %td.c{style: 'width: 50%;'}= display_in_percent @summary[activity][:stop_act], @summary[activity][:period]
                  %td.c{style: 'width: 50%;'}= display_in_percent @summary[activity][:drug_free], @summary[activity][:period]
            %td.c= pluralize(@summary[activity][:participants], 'Person')

            %td.c
              %table{style: 'width: 100%;'}
                %tr
                  %td.c= @summary[activity][:adult]
                  %td.c= @summary[activity][:youth]

            %td.c
              %table{style: 'width: 100%;'}
                %tr
                  %td.c{style: 'width: 50%'} 3
                  %td.c{style: 'width: 50%'} 60%
            %td.c
              %table{style: 'width: 100%'}
                %tr
                  %td.c{style: 'width: 15%'}= @summary[activity][:very]
                  %td.c{style: 'width: 15%'}= display_in_percent @summary[activity][:very], @summary[activity][:period]
                  %td.c{style: 'width: 17%'}= @summary[activity][:moderate]
                  %td.c{style: 'width: 17%'}= display_in_percent @summary[activity][:moderate], @summary[activity][:period]
                  %td.c{style: 'width: 16%'}= @summary[activity][:not_successful]
                  %td.c{style: 'width: 17%'}= display_in_percent @summary[activity][:not_successful], @summary[activity][:period]

app/views/static_pages/coalition_meeting_report.html.haml
- title "Coalition Meeting Report"

.row
  %br
  .col-md-2
    %strong Select Date Range
  .col-md-4
    .form-group
      .col-md-2
        %label From
      .col-md-10
        %input(id ='activity_date' class= 'form-control' data-date-format= "yyyy-mm-dd")
  .col-md-4
    .form-group
      .col-md-2
        %label To
      .col-md-10
        %input{id: 'activity_date1', class: 'form-control'}



.row
  %br
  .col-md-12
    %fieldset
      %legend Average Attendance
      .panel.panel-primary.form-group.question-panel
        .panel-heading How many people were involved in the activity?
        .panel-body
          10 People

    %fieldset
      %legend Sector Involvement
      .panel.panel-primary.form-group.question-panel
        .panel-heading What sectors were served by this activity?
        .panel-body
          .col-md-8
            .col-md-2 IT
            .col-md-6 - 20%
          .col-md-8
            .col-md-2 Retail
            .col-md-6 - 30%
          .col-md-8
            .col-md-2 Banking
            .col-md-6 - 40%

    %fieldset
      %legend Coalition Member Attendance
      .panel.panel-primary.form-group.question-panel
        .panel-heading Were any of the participants members of the coalition?
        .panel-body
          .col-md-8
            80%

    %fieldset
      %legend Coalition Member Involvement
      .panel.panel-primary.form-group.question-panel
        .panel-heading Calculation of coalition member attendance to the total attendance in (%).
        .panel-body
          .col-md-8
            .col-md-2 60-70%
            .col-md-6 - High

app/views/static_pages/coalition_report.html.haml
- title "User/Coalition Report"
.row
  .col-md-12
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th.c Sector
          %th.c # of Members/Users
          %th.c # Involvement (%)
      %tbody
        - @report.each_key do |sector|
          - next if sector == :involvement_total
          %tr
            %td.c= sector
            %td.c= @report[sector][:members]
            %td.c= "#{display_in_percent(@report[sector][:involvement], @report[:involvement_total])}"

app/views/static_pages/major_matrix_report.html.haml
- title "Major Matrix Report"
= form_tag major_matrix_report_path, method: :get do
  .row
    .col-md-12
      .form-group
        .col-md-10
          %table{style: 'width: 100%'}
            %tr
              %td.c{style: 'width: 15%'}
                %strong Search :
              %td{style: 'width: 35%'}
                = text_field_tag :start_date, '', class: 'form-control', data: { 'date-format' => 'yyyy-mm-dd' }, placeholder: 'Date From'
              %td{style: 'width: 35%'}
                = text_field_tag :end_date, '', class: 'form-control', data: { 'date-format' => 'yyyy-mm-dd' }, placeholder: 'Date To'
              %td.c{style: 'width: 15%'}
                = submit_tag('Search', class: 'btn btn-primary')



.row
  %br
  .col-md-12
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th.c Rank
          %th.c Activity
          %th.c Count(#)
          %th.c Count(%)
      %tbody
        - @activities.each_with_index do |(activity, value), index|
          %tr
            %td.c{style: 'width: 20%'}= "#{index + 1}"
            %td.c{style: 'width: 40%'}= activity
            %td.c{style: 'width: 20%'}= @activities[activity][:count]
            %td.c{style: 'width: 20%'}= display_in_percent @activities[activity][:count], Rapidfire::Attempt.count

app/views/static_pages/reports.html.haml
- title 'Reports'

.row
  .col-md-12
    = link_to 'User/Coalition Report', coalition_report_path, class: 'btn btn-primary'
    = link_to 'Coalition Meeting Report', coalition_meeting_report_path, class: 'btn btn-primary'
    = link_to 'Activity Summary', activity_summary_path, class: 'btn btn-primary'
    = link_to 'Major Matrix Report', major_matrix_report_path, class: 'btn btn-primary'
    = link_to 'Strategy Report', strategy_report_path, class: 'btn btn-primary'

app/views/static_pages/strategy_report.html.haml
- title "Major Matrix Report"
= form_tag strategy_report_path, method: :get do
  .row
    .col-md-12
      .form-group
        .col-md-10
          %table{style: 'width: 100%'}
            %tr
              %td.c{style: 'width: 15%'}
                %strong Search :
              %td{style: 'width: 35%'}
                = text_field_tag :start_date, '', class: 'form-control', data: { 'date-format' => 'yyyy-mm-dd' }, placeholder: 'Date From'
              %td{style: 'width: 35%'}
                = text_field_tag :end_date, '', class: 'form-control', data: { 'date-format' => 'yyyy-mm-dd' }, placeholder: 'Date To'
              %td.c{style: 'width: 15%'}
                = submit_tag('Search', class: 'btn btn-primary')



.row
  %br
  .col-md-12
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th.c Rank
          %th.c Strategy
          %th.c Count(#)
          %th.c Count(%)
      %tbody
        - @activities.each_with_index do |(activity, value), index|
          %tr
            %td.c{style: 'width: 20%'}= "#{index + 1}"
            %td.c{style: 'width: 40%'}= activity.html_safe
            %td.c{style: 'width: 20%'}= @activities[activity][:count]
            %td.c{style: 'width: 20%'}= display_in_percent @activities[activity][:count], Rapidfire::Attempt.count