config/routes.rb
SJYABackOffice::Application.routes.draw do
  resources :organizations

  resources :users do
    member do
      post 'invite', to: 'invites#create', as: :invite
      delete 'uninvite', to: 'invites#destroy', as: :uninvite
      get 'register/:invite_code', to: 'invites#edit', as: :rsvp
      match 'register', to: 'invites#update', via: [:patch, :put], as: :register
      match 'revoke', to: 'users#revoke', via: [:patch, :put], as: :revoke
    end
  end

  resources :documents do
    get 'download', on: :member, as: :download
  end

  resources :measures, except: [:show] do
    resources :measurements, except: [:index, :show]
  end
  get 'dashboard', to: 'measures#index', as: :dashboard

  resources :reports, only: [:index, :show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'cache/clear', to: 'cache#clear', as: :clear_caches

  get 'about', to: 'static_pages#about', as: :about
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout


  get 'reports', to: 'static_pages#reports', as: :reports
  get 'activity_summary', to: 'static_pages#activity_summary', as: :activity_summary
  get 'coalition_report', to: 'static_pages#coalition_report', as: :coalition_report
  get 'coalition_meeting_report', to: 'static_pages#coalition_meeting_report', as: :coalition_meeting_report
  get 'major_matrix_report', to: 'static_pages#major_matrix_report', as: :major_matrix_report
  get 'strategy_report', to: 'static_pages#strategy_report', as: :strategy_report

  mount Rapidfire::Engine => "/rf"

  root to: 'measures#index'
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  mount_uploader :item, DocumentUploader
  acts_as_taggable

  validates_presence_of :item

  before_save :set_default_title, :set_item_metadata

  scope :for_dashboard, -> { where(measurement_data: true) }

  def filename
    item.path.split('/').last
  end

  def name
    title || filename
  end

  def owner_name
    user.full_name
  end

  def for_dashboard?
    measurement_data
  end

  private

  def set_default_title
    self.title = self.filename if title.blank?
  end

  def set_item_metadata
    if item.present? && item_changed?
      self.item_size = item.file.size
      self.content_type = item.file.content_type
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :download, :edit, :update, :destroy]
  before_action :scope_documents, only: :index

  def index
  end

  def show
  end

  def download
    send_data (open @document.item.url).read,
      type: @document.content_type,
      filename: @document.filename,
      disposition: 'attachment'
  end

  def new
    @document = current_user.documents.build
    authorize! @document
  end

  def edit
  end

  def create
    @document = Document.new document_attributes
    @document.user = current_user
    authorize! @document

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors.messages.values.flatten, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @document.update document_attributes
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    def set_document
      @document = current_resource
      authorize! @document
    end

    def current_resource
      if params[:action] == 'create'
        @current_resource ||= params[:document] if params[:document]
      else
        @current_resource ||= Document.find(params[:id]) if params[:id]
      end
    end

    def document_attributes
      params.require(:document).permit *policy(@document || Document).permitted_attributes
    end

    def scope_documents
      @scopes = {}
      @title_scopes = {}
      @scope_params = {}

      if params[:owner] && User.exists?(params[:owner])
        @user = User.find params[:owner]
        @documents = @user.documents
        @title_scopes[:owner] = @scopes[:owner] = "owned by #{@user.full_name}"
        @scope_params[:owner] = params[:owner]
      else
        @documents = Document.includes(:user)
      end

      if params[:tag]
        @title_scopes[:tag] = "tagged with #{params[:tag].map{|tag| "'#{tag}'" }.join(' & ')}"
        @scopes[:tag] = params[:tag].map{|tag| "tagged with '#{tag}'"}
        @scope_params[:tag] = params[:tag]
        @documents = @documents.tagged_with params[:tag]
      end

      @documents = policy_scope @documents.order("#{sort_column} #{sort_direction}").page(params[:page]).per_page(15)
    end

    def sort_column
      super(Document.column_names + ['users.last_name'], 'updated_at')
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
  def file_type_label(filename = '')
    ext = filename.split('.').last
    _file_type_label *case ext
                      when /pdf/i
                        ['info', 'PDF']
                      when /jpe?g/i
                        ['warning', 'JPG']
                      when /png/i
                        ['warning', 'PNG']
                      when /gif/i
                        ['warning', 'GIF']
                      when /docx?/i
                        ['info', 'DOC']
                      when /pptx?/i
                        ['info', 'PPT']
                      when /xlsx?/i
                        ['info', 'XLS']
                      else
                        ['default', ext.upcase]
                      end
  end

  def render_tags(tag_list, current_scope = {})
    tag_list.map do |tag|
      tags = current_scope.has_key?(:tag) ? current_scope[:tag] : []
      link_to tag, current_scope.merge({tag: tags | [tag]}), class: 'btn btn-xs btn-default'
    end.join("&nbsp;").html_safe
  end

  private

  def _file_type_label(color, text)
    content_tag :span, text, class: "label label-#{color}"
  end
end

app/views/documents/_form.html.haml
= form_for @document, html: { multipart: true, class: 'form-horizontal' } do |f|
  = render partial: 'shared/form_errors', locals: { resource: @document }

  %fieldset
    .form-group
      = f.label :title, class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :title, class: 'form-control'

    .form-group
      = f.label :tag_list, 'Tags', class: 'control-label col-sm-2'
      .col-sm-10
        = f.text_field :tag_list, class: 'form-control'
        %span.help-block
          Separated by commas

    - if policy(@document).permitted_attributes.include? :measurement_data
      .form-group
        = f.label :measurement_data, 'Dashboard data?', class: 'control-label col-sm-2'
        .col-sm-10
          .checkbox
            %label
              = f.check_box :measurement_data
              = p_space 'Yes'

    .form-group
      = f.label :item, 'File', class: 'control-label col-sm-2'
      .col-sm-10
        = f.file_field :item

    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit class: 'btn btn-primary'
        = link_to 'Cancel', documents_path, class: 'btn btn-inverse'

app/views/documents/edit.html.haml
- title 'Edit Document'

- breadcrumbs ['Documents', documents_path], [@document.filename, document_path(@document)], 'Edit'

%br/

.row
  .col-md-12
    .box
      .box-header
        %h2
          %i.fa.fa-pencil

      .box-content
        .row
          .col-md-12
            = render 'form'

app/views/documents/index.html.haml
- title "Documents", true, @title_scopes.values.join(" ")

= render partial: 'shared/scope_tags', locals: { scopes: @scopes, scope_params: @scope_params }

.row
  .col-md-12
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th= sortable 'title', 'File'
          %th.c Tags
          - unless @scopes.has_key? :owner
            %th.c= sortable 'users.last_name', 'Owner'
          %th.c= sortable 'updated_at', 'Updated'
          %th.r

      %tbody
        - if @documents.any?
          - @documents.each do |document|
            %tr
              %td
                = file_type_label document.filename
                = "&nbsp;".html_safe
                = link_to document.name, document
                %small
                  %i= " (#{number_to_human_size document.item_size})"
              %td.c= render_tags document.tag_list, @scope_params
              - unless @scopes.has_key? :owner
                %td.c= link_to document.owner_name, documents_path(@scope_params.merge({owner: document.user_id}))
              %td.c
                = document.updated_at.strftime '%-m/%-d/%Y %-I:%M %p'
              %td.r
                .btn-group
                  = link_to download_document_path(document), title: "Download", class: 'btn btn-sm btn-success', data: { 'no-turbolink' => true } do
                    %i.fa.fa-download
                  - if policy(document).edit?
                    = link_to edit_document_path(document), title: "Edit Document", class: "btn btn-sm btn-warning" do
                      %i.fa.fa-pencil
                  - if policy(document).destroy?
                    = link_to document, title: "Remove", class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' }, method: :delete do
                      %i.fa.fa-trash-o
        - else
          %tr.warning
            %td{colspan: 5}
              No documents available.
              - if @user || params[:tag]
                = link_to 'View All', documents_path, class: 'btn-link'

    = will_paginate @documents

%br

.row
  .col-md-12
    = link_to new_document_path, class: 'btn btn-primary' do
      %i.fa.fa-plus
      = "&nbsp;New Document".html_safe

app/views/documents/new.html.haml
- title 'Document Uploader'

.row
  .col-md-12
    = form_for @document, html: { multipart: true, class: 'dropzone', data: { accepts: @document.item.extension_white_list.map{ |ext| ".#{ext}" } }} do |f|
      = render partial: 'shared/form_errors', locals: { resource: @document }

      %fieldset
        .row
          %ul.media-list.dropzone-previews

        .fallback
          .form-group
            = f.label :title
            = f.text_field :title, class: 'form-control'

          .form-group
            = f.label :item, 'File'
            = f.file_field :item

        %br/
        .well.well-lg.text-center.dropzone-activator
          %h1 Drop files to upload
          %h4 (or click)

        .form-group
          .col-sm-12
            = f.submit 'Upload', class: 'btn btn-primary'
            = link_to 'Cancel', documents_path, id: 'cancel-btn', class: 'btn btn-inverse'

        %span.badge.dz-message

%script{type: 'text/template', id: 'dz-preview-template'}
  %li.media.dz-preview.dz-file-preview
    .pull-left.media-object-container
      = image_tag 'file.png', size: "64x64", class: 'media-object', "data-dz-thumbnail" => true

    .media-body
      %h3.media-heading
        %span.dz-filename{"data-dz-name" => true}
        %small
          %span.separator= '|'
          %span.dz-size{"data-dz-size" => true}
          %span.separator= '|'
        %strong.dz-status.dz-queued-status.text-warning queued
        %strong.dz-status.dz-uploading-status.text-info uploading...
        %strong.dz-status.dz-success-status.text-success uploaded ✔
        %strong.dz-status.dz-error-status.text-danger failed ✘
        %small
          %span.separator= '|'
          %a.remove-file{href: '#'} remove

      .row
        .col-md-12
          .form-group
            .col-md-6
              %input.title-input.form-control{type: 'text', placeholder: 'Title'}
          - if policy(Document).permitted_attributes.include? :measurement_data
            .form-group.measurement-data-container
              .col-md-6
                .checkbox
                  %label
                    = check_box_tag :measurement_data, 1, false, class: 'measurement-data'
                    = p_space 'Dashboard Data Document?'

      .row
        .col-md-12
          .form-group
            .col-md-6
              %input.tags-input.form-control{type: 'text', placeholder: 'Tags', data: {tags: ActsAsTaggableOn::Tag.pluck(:name)}}

              .progress.progress-striped.dz-progress
                .progress-bar.progress-bar-info.dz-upload{"data-dz-uploadprogress" => true}

              .dz-error-message.text-danger{"data-dz-errormessage" => true}

app/views/documents/show.html.haml
- title @document.name, false

- breadcrumbs ['Documents', documents_path], @document.filename

%h1
  %i.fa.fa-hdd-o
  = p_space @document.name

%br/

.row
  .col-md-6
    %dl
      %dt
        %i.fa.fa-barcode
        = p_space 'Title'
      %dd= @document.title
      %br/

      %dt
        %i.fa.fa-file-text-o
        = p_space 'File'
      %dd= @document.filename
      %br/

      %dt
        %i.fa.fa-tags
        = p_space 'Tags'
      %dd= render_tags @document.tag_list

  .col-md-6
    %dl
      %dt
        %i.fa.fa-calendar
        = p_space 'Uploaded'
      %dd= @document.updated_at.strftime '%B %-d, %Y'
      %br/

      %dt
        %i.fa.fa-user
        = p_space 'Owner'
      %dd= link_to @document.user.full_name, @document.user

      - if policy(@document).permitted_attributes.include? :measurement_data
        %br/
        %dt
          - if @document.for_dashboard?
            %i.fa.fa-check.fa-lg.fa-border.text-success
          - else
            %i.fa.fa-times.fa-lg.fa-border.text-danger
          = p_space 'Dashboard Data File'

      - if policy(@document).edit?
        %br/
        %dd
          = link_to download_document_path(@document), title: "Download", class: 'btn btn-sm btn-success', data: { 'no-turbolink' => true } do
            %i.fa.fa-cloud-download
            = p_space 'Download'
          - if policy(@document).edit?
            = link_to edit_document_path(@document), title: "Edit Document", class: "btn btn-sm btn-warning" do
              %i.fa.fa-pencil
              = p_space 'Edit'
          - if policy(@document).destroy?
            = link_to @document, title: "Remove", class: "btn btn-sm btn-danger", data: { confirm: 'Are you sure?' }, method: :delete do
              %i.fa.fa-trash-o
              = p_space 'Remove'