config/routes.rb
SJYABackOffice::Application.routes.draw do
  resources :organizations

  resources :users do
    member do
      post 'invite', to: 'invites#create', as: :invite
      delete 'uninvite', to: 'invites#destroy', as: :uninvite
      get 'register/:invite_code', to: 'invites#edit', as: :rsvp
      match 'register', to: 'invites#update', via: [:patch, :put], as: :register
      match 'revoke', to: 'users#revoke', via: [:patch, :put], as: :revoke
    end
  end

  resources :documents do
    get 'download', on: :member, as: :download
  end

  resources :measures, except: [:show] do
    resources :measurements, except: [:index, :show]
  end
  get 'dashboard', to: 'measures#index', as: :dashboard

  resources :reports, only: [:index, :show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'cache/clear', to: 'cache#clear', as: :clear_caches

  get 'about', to: 'static_pages#about', as: :about
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout


  get 'reports', to: 'static_pages#reports', as: :reports
  get 'activity_summary', to: 'static_pages#activity_summary', as: :activity_summary
  get 'coalition_report', to: 'static_pages#coalition_report', as: :coalition_report
  get 'coalition_meeting_report', to: 'static_pages#coalition_meeting_report', as: :coalition_meeting_report
  get 'major_matrix_report', to: 'static_pages#major_matrix_report', as: :major_matrix_report
  get 'strategy_report', to: 'static_pages#strategy_report', as: :strategy_report

  mount Rapidfire::Engine => "/rf"

  root to: 'measures#index'
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :users
  belongs_to :sector
  mount_uploader :logo, LogoUploader
  validates_presence_of :name
  validates_presence_of :sector, unless: lambda {|org| org.name == 'LAN Resources' }

  after_save :clear_cache
  
  scope :assignable_for, ->(user) {
    case user.role
    when 'administrator'
      all
    when 'site_manager'
      where.not name: 'LAN Resources'
    when 'organization_manager'
      where id: user.organization_id
    else
      none
    end
  }

  private

  def clear_cache
    Rails.cache.delete 'sectors-by-user'
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.includes(:sector).order("#{sort_column} #{sort_direction}").page(params[:page]).per_page(25)
  end

  def show
    @organization = current_resource
    authorize! @organization
  end

  def new
    @organization = Organization.new
    authorize! @organization
  end

  def edit
    @organization = current_resource
    authorize! @organization
  end

  def create
    @organization = Organization.new organization_attributes
    authorize! @organization

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @organization = current_resource
    authorize! @organization

    respond_to do |format|
      if @organization.update(organization_attributes)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @organization = current_resource
    authorize! @organization

    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private
    def current_resource
      @current_resource ||= Organization.find(params[:id]) if params[:id]
    end

    def organization_attributes
      params.require(:organization).permit *policy(@organization || Organization).permitted_attributes
    end

    def sort_column
      super(Organization.column_names + ['sectors.name'], 'name')
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.haml
= form_for @organization, html: { class: 'form-horizontal', multipart: true } do |f|
  = render partial: 'shared/form_errors', locals: { resource: @organization }

  .form-group
    = f.label :name, class: 'control-label col-sm-2'
    .col-sm-10
      = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :sector_id, 'Sector', class: 'control-label col-sm-2'
    .col-sm-10
      = f.collection_select :sector_id, Sector.all, :id, :name, {}, class: 'form-control'

  .form-group
    = f.label :logo, 'Logo', class: 'control-label col-sm-2'
    .col-sm-10
      = f.file_field :logo

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: 'btn btn-primary'
      = link_to 'Cancel', organizations_path, class: 'btn btn-inverse'

app/views/organizations/edit.html.haml
- title "Edit Organization"

.row
  .col-lg-12
    .box
      .box-header
        %h2
          %i.fa.fa-globe
          = @organization.name
      .box-content
        = render 'form'

app/views/organizations/index.html.haml
- title "Organizations"

.row
  .col-md-12
    %table.table.table-striped.table-condensed
      %thead
        %tr
          %th
          %th= sortable 'name'
          %th= sortable 'sectors.name', 'Sector'
          %th.c Members
          - if policy(current_user.organization).edit?
            %th.r
      %tbody
        - @organizations.each do |org|
          %tr
            %td.photo= link_to image_tag(org.logo.url(:tiny), alt: "No Photo", class: 'img-rounded'), users_path({org: org.id})
            %td= link_to org.name, users_path({org: org.id})
            %td= org.sector.try(:name)
            %td.c= org.users.count
            - if policy(current_user.organization).edit?
              %td.r
                .btn-group.btn-group-xs
                  - if policy(org).edit?
                    = link_to edit_organization_path(org), title: "Edit Organization", class: "btn btn-xs btn-warning" do
                      %i.fa.fa-pencil
                  - if policy(org).destroy?
                    = link_to org, title: "Delete Organization", class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' }, method: :delete do
                      %i.fa.fa-trash-o

    = will_paginate @organizations

- if policy(Organization).create?
  .row
    .col-md-12
      = link_to "Add Organization", new_organization_path, class: 'btn btn-primary'

app/views/organizations/new.html.haml
- title "New Organization"

.row
  .col-lg-12
    .box
      .box-header
        %h2
          %i.fa.fa-globe
      .box-content
        = render 'form'

app/views/organizations/show.html.haml
- title @organization.name

- breadcrumbs ['Organizations', organizations_path], @organization.name

.row
  .col-lg-12
    .box
      .box-header
        %h2
          %i.fa.fa-globe
        .box-icon
          = link_to edit_organization_path(@organization), title: 'Edit' do
            %i.fa.fa-pencil

      .box-content
        .row
          .col-md-2
            = image_tag(@organization.logo.url(:small), class: "img-rounded")
          .col-md-5
            %h4= pluralize @organization.users.count, 'member'