config/routes.rb
SJYABackOffice::Application.routes.draw do
  resources :organizations

  resources :users do
    member do
      post 'invite', to: 'invites#create', as: :invite
      delete 'uninvite', to: 'invites#destroy', as: :uninvite
      get 'register/:invite_code', to: 'invites#edit', as: :rsvp
      match 'register', to: 'invites#update', via: [:patch, :put], as: :register
      match 'revoke', to: 'users#revoke', via: [:patch, :put], as: :revoke
    end
  end

  resources :documents do
    get 'download', on: :member, as: :download
  end

  resources :measures, except: [:show] do
    resources :measurements, except: [:index, :show]
  end
  get 'dashboard', to: 'measures#index', as: :dashboard

  resources :reports, only: [:index, :show]

  resources :sessions, only: [:new, :create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]

  get 'cache/clear', to: 'cache#clear', as: :clear_caches

  get 'about', to: 'static_pages#about', as: :about
  get 'login', to: 'sessions#new', as: :login
  delete 'logout', to: 'sessions#destroy', as: :logout


  get 'reports', to: 'static_pages#reports', as: :reports
  get 'activity_summary', to: 'static_pages#activity_summary', as: :activity_summary
  get 'coalition_report', to: 'static_pages#coalition_report', as: :coalition_report
  get 'coalition_meeting_report', to: 'static_pages#coalition_meeting_report', as: :coalition_meeting_report
  get 'major_matrix_report', to: 'static_pages#major_matrix_report', as: :major_matrix_report
  get 'strategy_report', to: 'static_pages#strategy_report', as: :strategy_report

  mount Rapidfire::Engine => "/rf"

  root to: 'measures#index'
end

app/models/measure.rb
class Measure < ActiveRecord::Base
  belongs_to :source
  belongs_to :document
  has_many :measurements, dependent: :destroy

  validates_presence_of :description, :source

  before_save :clean

  private

  def clean
    if link && link.blank?
      self.link = nil
    end
  end
end

app/controllers/measures_controller.rb
class MeasuresController < ApplicationController

  def index
    @measures = Measure.includes(:source, :measurements).order(:created_at)
    @measurements = Measurement.includes(:measure).tap{|m| @years = m.pluck(:year).uniq.sort }.to_a.group_by{|m| [m.measure_id, m.year]}
  end

  def new
    @measure = Measure.new
    authorize! @measure

    respond_to do |format|
      format.js { render 'modal' }
    end
  end

  def edit
    @measure = current_resource
    authorize! @measure

    respond_to do |format|
      format.js { render 'modal' }
    end
  end

  def create
    @measure = Measure.new measure_attributes
    authorize! @measure

    respond_to do |format|
      if @measure.save
        format.html { redirect_to root_url, notice: 'Measure was successfully created.' }
        format.js {
          @years = Measurement.pluck(:year).uniq.sort
          @show_new_year_column = !@years.include?(Date.today.year) && policy(Measurement).create?
        }
      else
        format.html { redirect_to root_url }
        format.js { render 'error' }
      end
    end
  end

  def update
    @measure = current_resource
    authorize! @measure

    respond_to do |format|
      if @measure.update(measure_attributes)
        format.html { redirect_to root_url, notice: 'Measure was successfully updated.' }
        format.json { respond_with_bip(@measure) }
        format.js {
          @measurements = Measurement.includes(:measure).tap{|m| @years = m.pluck(:year).uniq.sort }.where(measure_id: @measure.id).to_a.group_by{|m| [m.measure_id, m.year]}
          @show_new_year_column = !@years.include?(Date.today.year) && policy(Measurement).create?
        }
      else
        format.html { redirect_to root_url }
        format.json { respond_with_bip(@measure) }
        format.js { render 'error' }
      end
    end
  end

  def destroy
    @measure = current_resource
    authorize! @measure

    @measure.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  private
    def current_resource
      @current_resource ||= Measure.find(params[:id]) if params[:id]
    end

    def measure_attributes
      params.require(:measure).permit *policy(@measure || Measure).permitted_attributes
    end
end

app/helpers/measures_helper.rb
module MeasuresHelper
  def measure_link(measure)
    if measure.link
      link_to measure.link, target: '_blank', title: measure.link do
        content_tag :i, nil, class: 'fa fa-external-link'
      end.html_safe
    end
  end

  def measure_document_link(measure)
    if doc = measure.document
      link_to download_document_path(doc), title: doc.name, target: :_blank do
        content_tag :i, nil, class: 'fa fa-file-text'
      end.html_safe
    end
  end

  def cached_measure_permissions
    @measure_permissions ||= begin
      measure_policy = policy(Measure)
      measurement_policy = policy(Measurement)
      {
        update_measure: measure_policy.update?,
        create_measurement: measurement_policy.create?,
        edit_measurement: measurement_policy.edit?,
        update_measurement: measurement_policy.update?,
        destroy_measurement: measurement_policy.destroy?
      }
    end
  end
end

app/views/measures/_measure.html.haml
- cache [cached_measure_permissions[:update_update_measure], measure, years.join('-')] do
  %tr.measure{data: {measure: measure.id }}
    %td.measure-description
      = best_in_place_if cached_measure_permissions[:update_measure], measure, :description, inner_class: 'form-control'
      = p_space measure_link(measure)
      = p_space measure_document_link(measure)
      - if cached_measure_permissions[:update_measure]
        .btn-group.btn-group-xs.modifiers.pull-right
          = link_to edit_measure_path(measure), remote: true, title: "Edit Measure", class: "btn btn-xs btn-warning" do
            %i.fa.fa-pencil
          = link_to measure, title: "Remove", class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' }, remote: true, method: :delete do
            %i.fa.fa-trash-o
    %td.c.measure-source
      %abbr{title: measure.source.name}= measure.source.short_name
    - years.each do |year|
      - measurement = measurements.has_key?([measure.id, year]) ? measurements[[measure.id, year]].first : nil
      = render partial: 'measurement', locals: {measurement: measurement, measure: measure, year: year, modifiers: false }
    - if show_new_year_column
      = render partial: 'measurement', locals: {measurement: nil, measure: measure, year: Date.today.year, modifiers: true }

app/views/measures/_measurement.html.haml
- if measurement
  - if cached_measure_permissions[:update_measurement]
    %td.c.measurement{data: {year: year, measure: measure.id, measurement: measurement.id }}
      %span.popovers{data: {content: render(partial: 'measures/popover', locals: { measure: measure, measurement: measurement }).html_safe}}
        = measurement.value
  - else
    %td.c
      = measurement.value
      - if measurement.link || measurement.document
        %br/
        = p_space measure_link(measurement)
        = p_space measure_document_link(measurement)

- else
  - if cached_measure_permissions[:create_measurement]
    %td.c.no-measurement{class: ('modifiers new-year' if modifiers), data: {year: year, measure: measure.id, path: new_measure_measurement_path(measure, {year: year})}}
      = '-'
  - else
    %td.c= '-'

app/views/measures/_modal.html.haml
- new_or_edit = measure.new_record? ? 'new' : 'edit'
.modal.fade{id: "#{new_or_edit}-measure-modal", role: 'dialog', aria: {labelledby: "#{new_or_edit}-measure-modal-label", hidden: 'true'}}
  .modal-dialog
    .modal-content
      = form_for measure, remote: true, html: { class: 'form-horizontal' } do |f|
        .modal-header
          %button.close{type: 'button', data: {dismiss: 'modal'}, aria: {hidden: 'true'}} &times;
          %h4.modal-title{id: "#{new_or_edit}-measure-modal-label"}= "#{new_or_edit.titleize} Measure"

        .modal-body
          .form-group
            = f.label :description, class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :description, class: 'form-control'

          .form-group
            = f.label :source_id, 'Source', class: 'control-label col-sm-2'
            .col-sm-10
              = f.collection_select :source_id, Source.all, :id, :name, {}, class: 'form-control'

          .form-group
            = f.label :link, class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :link, class: 'form-control'

          .form-group
            = f.label :document_id, class: 'control-label col-sm-2'
            .col-sm-10
              = f.collection_select :document_id, Document.for_dashboard, :id, :name, {include_blank: true}, class: 'form-control'

        .modal-footer
          %button.btn.btn-default{type: 'button', data: {dismiss: 'modal'}} Close
          = f.submit class: 'btn btn-primary'

app/views/measures/_new_measure_modal.html.haml
.modal.fade#new-measure-modal{role: 'dialog', aria: {labelledby: 'new-measure-modal-label', hidden: 'true'}}
  .modal-dialog
    .modal-content
      = form_for Measure.new, html: { class: 'form-horizontal' } do |f|
        .modal-header
          %button.close{type: 'button', data: {dismiss: 'modal'}, aria: {hidden: 'true'}} &times;
          %h4.modal-title#new-measure-modal-label New Measure

        .modal-body
          .form-group
            = f.label :description, class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :description, class: 'form-control'

          .form-group
            = f.label :source_id, 'Source', class: 'control-label col-sm-2'
            .col-sm-10
              = f.collection_select :source_id, Source.all, :id, :name, {}, class: 'form-control'

          .form-group
            = f.label :link, class: 'control-label col-sm-2'
            .col-sm-10
              = f.text_field :link, class: 'form-control'

          .form-group
            = f.label :document_id, class: 'control-label col-sm-2'
            .col-sm-10
              = f.collection_select :document_id, Document.for_dashboard, :id, :name, {include_blank: true}, class: 'form-control'

        .modal-footer
          %button.btn.btn-default{type: 'button', data: {dismiss: 'modal'}} Close
          = f.submit 'Create', class: 'btn btn-primary'

app/views/measures/_popover.html.haml
.btn-group-vertical
  = measurement_popover_link measurement
  = measurement_popover_document_link measurement
  - if cached_measure_permissions[:edit_measurement]
    = link_to edit_measure_measurement_path(measure, measurement), remote: true, title: "Edit Measurement", class: "btn btn-xs btn-warning" do
      %i.fa.fa-pencil
  - if cached_measure_permissions[:destroy_measurement]
    = link_to [measure, measurement], title: "Remove", class: "btn btn-xs btn-danger", data: { confirm: 'Are you sure?' }, remote: true, method: :delete do
      %i.fa.fa-trash-o

app/views/measures/index.html.haml
- title 'Dashboard'

.row
  .col-md-12
    .table-responsive
      %table.table.table-striped.table-condensed#measure-table{data: {years: @years}}
        %thead
          %tr
            %th Measure
            %th.c Source
            - @years.each do |year|
              %th.c= year
            - if show_new_year_column = !@years.include?(Date.today.year) && cached_measure_permissions[:create_measure]
              %th.c.modifiers.new-year= Date.today.year
        %tbody
          = render partial: 'measure', collection: @measures, locals: {years: @years, measurements: @measurements, show_new_year_column: show_new_year_column }

- if cached_measure_permissions[:update_measure]
  .row
    .col-md-12
      %button.btn.btn-primary#admin-mode-toggle{data: {toggle: 'button'}}
        %i.fa.fa-wrench
        = p_space 'Admin Mode:'
        %span.state= p_space 'Off'

      - if cached_measure_permissions[:create_measure]
        = link_to new_measure_path, class: 'btn btn-primary', remote: true do
          %i.fa.fa-plus
          = p_space 'New Measure'